### ISSUE TITLE
results are being forced to a limit of 20 if no limit is provided

### ISSUE THREAD

**Issue by mikedevita** [VAMSApp/onair-api#31]
The results are being forced to 20 if no limit parameter is provided, I suggest that we change the `limit` parameter to optional. This should not affect any downstream negatively.

**example**
[getVirtualAirlineFlights.ts](https://github.com/VAMSApp/onair-api/blob/18b3f085f438c108fbaa17a514e0d1ed7d3b2f1e/src/api/getVirtualAirlineFlights.ts#L7)
```typescript
async (vaId: string, apiKey: string, page = 1, limit = 20)
```

**proposed**
getVirtualAirlineFlights.ts
```typescript
async (vaId: string, apiKey: string, page = 1, limit?:number)
```

**Comment by mikedevita** [comment]
Hey @logicbox can you check to see if these proposed changes will impact anything regarding the `onair-cli` lib? If not I will plan to merge this into master and create a new version at the end of next week.

**Comment by logicbox** [comment]
Hi Mike, sorry for tardy reply, it doesn't look like I rely on the limit enforced here, so no problems with this.
